module.exports = {
    SET_FIREBASE_TOKEN: 'SET_FIREBASE_TOKEN',
    FETCH_POST_REQUESTED: 'FETCH_POST_REQUESTED',
    FETCH_POST_SUCCEEDED: 'FETCH_POST_SUCCEEDED',
    FETCH_POST_FAILED: 'FETCH_POST_FAILED'
}